// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAz27tfPeuUb7HMhoSw1l2zMPbZHCkt1Y',
    appId: '1:56003422609:web:43b8457147586753581230',
    messagingSenderId: '56003422609',
    projectId: 'bc-demo-44137',
    authDomain: 'bc-demo-44137.firebaseapp.com',
    storageBucket: 'bc-demo-44137.appspot.com',
    measurementId: 'G-48T316LP4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGdk4PQpIGgc_wsy9u11cUq09GajlHPX0',
    appId: '1:56003422609:android:c4e99a2450f019f5581230',
    messagingSenderId: '56003422609',
    projectId: 'bc-demo-44137',
    storageBucket: 'bc-demo-44137.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2fsl-k0qRXkWoO5_ZnQiegxrtzUwkJz4',
    appId: '1:56003422609:ios:6170e0f7b5566400581230',
    messagingSenderId: '56003422609',
    projectId: 'bc-demo-44137',
    storageBucket: 'bc-demo-44137.appspot.com',
    iosClientId: '56003422609-op717addqfjepcub743uq8slpmpt64g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.dapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2fsl-k0qRXkWoO5_ZnQiegxrtzUwkJz4',
    appId: '1:56003422609:ios:6170e0f7b5566400581230',
    messagingSenderId: '56003422609',
    projectId: 'bc-demo-44137',
    storageBucket: 'bc-demo-44137.appspot.com',
    iosClientId: '56003422609-op717addqfjepcub743uq8slpmpt64g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.dapp',
  );
}
